// Mock data for community feed — replace with Supabase queries when configured
export const MOCK_POSTS = [
  {
    id: 'post-1',
    user_id: 'user-1',
    region: 'Lonavala',
    purpose: 'Investment',
    budget_min: 5000000,
    budget_max: 15000000,
    size_value: 20,
    size_unit: 'Guntha',
    description: 'Looking for NA-converted farmhouse plot near Lonavala expressway. Clear title mandatory. Open to joint development if owner is interested.',
    upvote_count: 24,
    reply_count: 7,
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    users_profile: { display_name: 'Rahul M.', is_verified_owner: false },
  },
  {
    id: 'post-2',
    user_id: 'user-2',
    region: 'Karjat',
    purpose: 'Personal Use',
    budget_min: 2500000,
    budget_max: 6000000,
    size_value: 10,
    size_unit: 'Guntha',
    description: 'Weekend home land requirement. Prefer river-facing or hilltop plot. Road access essential. NA plot preferred, will also consider conversion.',
    upvote_count: 18,
    reply_count: 4,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    users_profile: { display_name: 'Priya S.', is_verified_owner: false },
  },
  {
    id: 'post-3',
    user_id: 'user-3',
    region: 'Goa',
    purpose: 'Resale',
    budget_min: 20000000,
    budget_max: 50000000,
    size_value: 1,
    size_unit: 'Acre',
    description: 'Investor looking for Goa land for quick turnaround. RERA-approved preferred. North Goa coastal belt highly desired. Serious buyer with funds ready.',
    upvote_count: 41,
    reply_count: 12,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    users_profile: { display_name: 'Amit K.', is_verified_owner: true },
  },
  {
    id: 'post-4',
    user_id: 'user-4',
    region: 'Igatpuri',
    purpose: 'Investment',
    budget_min: 3000000,
    budget_max: 8000000,
    size_value: 15,
    size_unit: 'Guntha',
    description: 'Searching tribal-free agricultural land near Igatpuri. Prefer direct owner dealings. Budget negotiable for right opportunity.',
    upvote_count: 9,
    reply_count: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    users_profile: { display_name: 'Suresh T.', is_verified_owner: false },
  },
  {
    id: 'post-5',
    user_id: 'user-5',
    region: 'Other',
    purpose: 'Investment',
    budget_min: 10000000,
    budget_max: 30000000,
    size_value: 2,
    size_unit: 'Acre',
    description: 'Looking for Maharashtra highway-facing commercial land. NH48 or NH66 belt preferred. Clear NOC from relevant authorities required.',
    upvote_count: 15,
    reply_count: 5,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    users_profile: { display_name: 'Deepa R.', is_verified_owner: true },
  },
];

export const MOCK_REPLIES = {
  'post-1': [
    { id: 'r-1', post_id: 'post-1', user_id: 'u-a', body: 'We have a 22 Guntha NA plot near Imagica, proper road access, price negotiable. DM for details.', created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(), users_profile: { display_name: 'Owner_PN', is_verified_owner: true } },
    { id: 'r-2', post_id: 'post-1', user_id: 'u-b', body: 'What\'s your preferred timeline for closing? We have a few parcels in the pipeline.', created_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(), users_profile: { display_name: 'HavenAgent', is_verified_owner: false } },
  ],
  'post-3': [
    { id: 'r-3', post_id: 'post-3', user_id: 'u-c', body: 'North Goa 1.2 acre parcel with clear title. Zone: agricultural. Open to talk. Serious owners only.', created_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(), users_profile: { display_name: 'GoaLandOwner', is_verified_owner: true } },
  ],
};
